exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/emzeat/mz-lictools
    rev: v2.4.4
    hooks:
      - id: license-tools

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
    hooks:
        - id: django-upgrade
          args: [ --target-version, "5.0" ]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.3
    hooks:
      - id: shellcheck

  - repo: https://github.com/rtts/djhtml
    rev: v1.4.11
    hooks:
      - id: djhtml
        args:
          - --tabwidth=2

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or:
          - css
          - xml
        additional_dependencies:
          - prettier@2.5.1
          - '@prettier/plugin-xml@1.2.0'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.6.0
    hooks:
      - id: eslint
        args:
          - --fix
        additional_dependencies:
          - eslint@8.6.0
          - eslint-config-google@0.14.0
          - eslint-config-prettier@8.3.0

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.0
    hooks:
      - id: curlylint
        additional_dependencies:
              - click==8.0.4

  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: rye check
        language: system
        files: \.py$

      - id: pyright
        name: Run pyright type checking
        entry: rye run pyright
        language: system
        files: \.py$

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==21.12b0


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
