site_name: Django-Quotes Documentation
copyright: Copyright &copy; 2022 Daniel Andrlik
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - "Managing Sources & Quotes": managing_quotes.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Security: security.md
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: deep-purple
repo_url: https://github.com/andrlik/django-quotes/
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import django"
            - "django.setup()"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
