site_name: Django-Quotes Documentation
site_url: https://andrlik.github.io/django-quotes/
site_author: Daniel Andrlik
copyright: Copyright &copy; 2022 Daniel Andrlik
atch: [mkdocs.yml, README.md, CHANGELOG.md, CODE_OF_CONDUCT.md, SECURITY.md, src/django_quotes]
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - "Managing Sources & Quotes": managing_quotes.md
  - Reference: reference/
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Security: security.md
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: indigo
    accent: deep-purple
repo_url: https://github.com/andrlik/django-quotes/
plugins:
  - search
  - autorefs
  - include-markdown
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_files.py
  - literate-nav:
      nav_file: SUMMARY.txt
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import django"
            - "django.setup()"
  - mike:
      canonical_version: latest
          options:
            separate_signature: true
            show_signature_annotations: true
            merge_init_into_class: true
            annotations_path: brief
            docstring_options:
              ignore_init_summary: true
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - footnotes

extra:
  version:
    provider: mike
