# Generated by Django 5.0.4 on 2024-04-26 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_markov", "0005_alter_markovtextmodel_data"),
        ("django_quotes", "0013_remove_quote_quote_rendered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="text_model",
            field=models.OneToOneField(
                blank=True,
                help_text="The text model for this character.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_markov.markovtextmodel",
            ),
        ),
        migrations.AlterField(
            model_name="sourcegroup",
            name="text_model",
            field=models.OneToOneField(
                blank=True,
                help_text="The markov model for this group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_markov.markovtextmodel",
            ),
        ),
    ]
