name: "Publish"

on:
  release:
    types: ["published"]

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  DJANGO_DEBUG: "1"

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        run: uv python install 3.12

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-publish-py312-${{ hashFiles('uv.lock') }}
          restore-keys: venv-publish-py312-

      - name: Create venv, install dependencies
        run: |
          uv sync
          source .venv/bin/activate
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
